name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out Code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build
        run: make build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Docker Build
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-458014/notely-ar-repo/notely:latest

      - name: Deploy Docker Image to Google Cloud Run
        run: |
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/notely-458014/notely-ar-repo/notely:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project ${{ secrets.NOTELY_ID }}

      - name: Set Max Instances
        run: |
          gcloud run services update notely \
            --region us-central1 \
            --max-instances=4 \
            --project ${{ secrets.NOTELY_ID }}
